DROP TABLE IF EXISTS USER;

CREATE TABLE USER(
    USER_ID INTEGER IDENTITY PRIMARY KEY,
    USERS_NAME VARCHAR(45) NOT NULL,
    USERS_PASSWORD VARCHAR(45) NOT NULL,
    EMAIL VARCHAR(45) NOT NULL,
    INITIAL_DATE DATETIME NOT NULL
);

DROP TABLE IF EXISTS SONG;
CREATE TABLE SONG(
    SONG_ID INTEGER IDENTITY PRIMARY KEY,
    SONG_NAME VARCHAR(100) NOT NULL,
    SONG_ARTIST VARCHAR(45) NOT NULL,
    RELEASE_DATE DATETIME NOT NULL,
    ALBUM VARCHAR(45) NOT NULL,
    GENRE VARCHAR(45) NOT NULL
);

DROP TABLE IF EXISTS ALBUM;

CREATE TABLE ALBUM(
    ALBUM_ID INTEGER IDENTITY PRIMARY KEY,
    ALBUM_NAME VARCHAR(45) NOT NULL,
    ALBUM_ARTIST VARCHAR(45) NOT NULL,
    RELEASE_DATE DATETIME NOT NULL,
    GENRE VARCHAR(45) NOT NULL
);
DROP TABLE IF EXISTS ARTIST;

CREATE TABLE ARTIST(
    ARTIST_ID INTEGER IDENTITY PRIMARY KEY,
    ARTIST_NAME VARCHAR(45) NOT NULL
);

DROP TABLE IF EXISTS EPISODE;

CREATE TABLE EPISODE(
    EPISODE_ID INTEGER IDENTITY PRIMARY KEY,
    EPISODE_NAME VARCHAR(45) NOT NULL,
    PARTICIPANTS_NAME VARCHAR(45) NOT NULL,
    TOPIC VARCHAR(45) NOT NULL
);